version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - mynetwork
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
  
  server:
    build:
      context: nginx
    container_name: server
    networks:
      - mynetwork
    tty: true
    ports:
      - "80:80"
  
  database:
    image: mysql:5.7
    command: "--innodb-use-native-aio=0"
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./startdb:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
